theme = 'relearn'
canonifyURLs = true
relativeURLs = true
title = "ChemImage LCTF"

[outputs]
home = [ "HTML", "RSS", "JSON"]

[params]
  themeVariant = "blue"
  externalLinkTarget = ""
  titleSeparator = ""