name: Package

on: [push]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        version: '3.1.100'

    - name: Setup Nuget.exe
      uses: NuGet/setup-nuget@v1.0.2
      with:
        nuget-version: 'latest'

    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.0.0

    - name: Build wix projects
      run: |
        nuget sources Add -Name "GPR" -Source "https://nuget.pkg.github.com/ChemImageFT/index.json" -Username aklein53 -Password ${{ secrets.nugetToken }}
        dotnet build "Installer/LCTF SDK Installer.sln" --configuration Release
        msbuild Installer/SdkSetup/SdkSetup.wixproj -property:configuration=Release
        msbuild Installer/SdkBootstrapper/SdkBootstrapper.wixproj -property:configuration=Release